name: Deployment from Github to AWS
on:
  push:
    branches:
    - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: 'Create env file'
        run: |
          touch .env
          echo APP_PORT=8080 >> .env
          echo APP_CONTAINER_NAME="django" >> .env
          cat .env
          ls -la
          pwd

      - name: build and run container
        env:
          APP_PORT: 8080
          APP_CONTAINER_NAME: django
        run: docker-compose up -d --build

      - name: run tests
        run: docker-compose exec django pytest

      - name: stop containers
        run: docker-compose down